# Generated by Django 4.2.16 on 2024-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_nickname",
                    models.CharField(
                        default="", max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("usar_name", models.CharField(default="", max_length=100)),
                (
                    "user_email",
                    models.EmailField(default="", max_length=100, unique=True),
                ),
                ("user_age", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
